
//HEAD
import Head from "next/head";
import { Inter } from "@next/font/google";
//const inter = Inter({ subsets: ["latin"] });
//STYLES
import styles from "./styles/Home.module.scss";
//LINK
import Link from "next/link";
//CARD

//ROUTER

import AsideNav from "./components/AsideNav";
//IMAGES
import Image from "next/image";
import img1 from "../public/images/img1.jpg";
import img2 from "../public/images/img2.jpg";
import img3 from "../public/images/img3.jpg";
import img4 from "../public/images/img4.jpg";
import img5 from "../public/images/img5.jpg";
import img6 from "../public/images/img6.png";
import img7 from "../public/images/img7.jpg";
import img8news from "../public/images/img8news.jpg";

import CardArticles from "./components/CardArticles";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";



export default function Home() {


  return (
    <>
      <Head>
        <title>Blog Thierry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <div className={styles.index_container_h1}>
          <h1>EICERAMIQUE</h1>
          {/** <p>Router ={router.asPath}</p>*/}
        </div>
        <section className={styles.home_section_container}>
          {/**type de card */}
          <Link className={styles.home_Link} href={"/articles"}>
            <Image
              className={styles.home_Images}
              src={img1}
              alt="Picture of the author"
              width={3988}
              height={5982}
              placeholder="blur"
            />

            <CardArticles
            />
          </Link>
          {/** card 2*/}
          <Link className={styles.home_Link} href={"/articles/atelier"}>
            <Image
              className={styles.home_Images_widh_differente_les_ateliers}
              src={img2}
              alt="Picture of the author"
              width={640}
              height={960}
              placeholder="blur"
            />
            <CardArticles/>
          </Link>
          {/**card 3 */}
          <Link className={styles.home_Link} href={"/articles/four"}>
            <Image
              className={styles.home_Images_widh_differente}
              src={img3}
              alt="Picture of the author"
              width={640}
              height={427}
              placeholder="blur"
            />
            <CardArticles/>
          </Link>
          {/**card 4 */}
          <Link className={styles.home_Link} href={"/articles/tour"}>
            <Image
              className={styles.home_Images}
              src={img4}
              alt="Picture of the author"
              width={640}
              height={427}
              placeholder="blur"
            />
            <CardArticles />
          </Link>
          {/**card 5 */}
          <Link className={styles.home_Link} href={"/articles/tournage"}>
            <Image
              className={styles.home_Images}
              src={img5}
              alt="Picture of the author"
              width={375}
              height={375}
              placeholder="blur"
            />
            <CardArticles/>
          </Link>
          {/**card 6 */}
          <Link className={styles.home_Link} href={"/articles/nouveauarticle"}>
            <Image
              className={styles.home_Images}
              src={img8news}
              alt="Picture of the author"
              width={640}
              height={706}
            />
            <CardArticles />
          </Link>
          {/**card 7 */}
          <Link className={styles.home_Link} href={"/web"}>
            <Image
              className={styles.home_Images_widh_differente}
              src={img6}
              alt="Picture of the author"
              width={1847}
              height={867}
            />
            <CardArticles/>
          </Link>
          {/**card 8 */}
          <Link className={styles.home_Link} href={"/contact"}>
            <Image
              className={styles.home_Images_widh_differente}
              src={img7}
              alt="Picture of the author"
              width={640}
              height={427}
            />
            <CardArticles/>
          </Link>
         
        </section>
        <AsideNav />
      
      </main>
      <Footer />
    </>
  );
}
